name:                template-library
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/sbditto85/template-library#readme
license:             BSD3
author:              Casey Allred
maintainer:          sbditto85@gmail.com
copyright:           2022 Casey Allred
category:            Messaging
extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
  - base >= 4.7 && < 10
  - classy-prelude >= 1.5 && < 2
  - free
  - shakespeare
  - text
  - transformers

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  expirementation-rio-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
      - template-library
      - hspec

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
